import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next.js - facts about cats",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex gap-20 mt-5 pl-10 pt-2 w-full  text-black font-bold text-xl  ">
					<Link
						href="/"
						className="hover:text-rose-900/80 transition hover:delay-100"
					>
						Home
					</Link>
					<Link
						href="/rendering/ssg"
						className="hover:text-rose-900/80 transition hover:delay-100"
					>
						SSG
					</Link>
					<Link
						href="/rendering/isr"
						className="hover:text-rose-900/80 transition hover:delay-100"
					>
						ISR
					</Link>
					<Link
						href="/rendering/ssr"
						className="hover:text-rose-900/80 transition hover:delay-100"
					>
						SSR
					</Link>
					<Link
						href="/rendering/csr"
						className="hover:text-rose-900/80 transition hover:delay-100"
					>
						CSR
					</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
